In [65]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [66]:
df=pd.read_csv("Student_Performance.csv")

In [67]:
df.head()

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,Yes,9,1,91.0
1,4,82,No,4,2,65.0
2,8,51,Yes,7,2,45.0
3,5,52,Yes,5,2,36.0
4,7,75,No,8,5,66.0

In [68]:
df.isnull().sum()

Hours Studied                       0
Previous Scores                     0
Extracurricular Activities          0
Sleep Hours                         0
Sample Question Papers Practiced    0
Performance Index                   0
dtype: int64

In [69]:
df.drop_duplicates(inplace=True)

## Encoding

### Label Encoding

In [72]:
from sklearn.preprocessing import LabelEncoder

In [73]:
encoder=LabelEncoder()

In [74]:
df["Extracurricular Activities"]=encoder.fit_transform(df["Extracurricular Activities"])

In [75]:
df.head()

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,1,9,1,91.0
1,4,82,0,4,2,65.0
2,8,51,1,7,2,45.0
3,5,52,1,5,2,36.0
4,7,75,0,8,5,66.0

## Train Test Split

In [77]:
x=df.drop("Performance Index",axis=1)

In [78]:
y=df["Performance Index"]

In [79]:
from sklearn.model_selection import train_test_split

In [94]:
x.shape

(9873, 5)

In [96]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=33)

In [98]:
xtrain.shape

(7898, 5)

In [100]:
xtest.shape

(1975, 5)

In [102]:
ytrain.shape

(7898,)

In [104]:
ytest.shape

(1975,)

## Scaler

In [107]:
from sklearn.preprocessing import StandardScaler

In [109]:
scaler=StandardScaler()

In [111]:
xtrain_scaled=scaler.fit_transform(xtrain)

In [115]:
xtrain.head()

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced
1550,6,97,1,9,2
2744,1,41,1,5,5
3851,5,77,0,7,9
1870,2,71,1,8,8
6606,1,80,0,9,0

In [119]:
xtrain_scaled

array([[ 3.85655186e-01,  1.59478896e+00,  1.00405990e+00,
         1.46296450e+00, -9.08838580e-01],
       [-1.54898954e+00, -1.63470048e+00,  1.00405990e+00,
        -8.97865782e-01,  1.41294128e-01],
       [-1.27375951e-03,  4.41399871e-01, -9.95956516e-01,
         2.82549357e-01,  1.54147107e+00],
       ...,
       [ 1.54644202e+00, -1.11567539e+00, -9.95956516e-01,
        -8.97865782e-01,  1.19142684e+00],
       [ 1.15951308e+00,  1.30644169e+00, -9.95956516e-01,
        -3.07658213e-01,  8.41382601e-01],
       [-3.88202705e-01,  1.71012787e+00,  1.00405990e+00,
         2.82549357e-01,  8.41382601e-01]])

# Model Building

## Linear Regression

In [123]:
from sklearn.linear_model import LinearRegression

In [125]:
model=LinearRegression()

In [127]:
model.fit(xtrain_scaled,ytrain)

LinearRegression()

## Prediction

In [130]:
xtest_scaled=scaler.transform(xtest)
xtest_scaled

array([[-3.88202705e-01, -1.28868376e+00,  1.00405990e+00,
         2.82549357e-01, -1.60892705e+00],
       [ 1.54644202e+00,  1.71012787e+00, -9.95956516e-01,
        -8.97865782e-01,  4.91338364e-01],
       [-1.16206060e+00, -1.11567539e+00,  1.00405990e+00,
         8.72756927e-01, -9.08838580e-01],
       ...,
       [ 1.15951308e+00, -4.81311398e-01, -9.95956516e-01,
        -8.97865782e-01,  8.41382601e-01],
       [-3.88202705e-01,  1.13343332e+00, -9.95956516e-01,
        -3.07658213e-01, -5.58794344e-01],
       [-1.27375951e-03, -5.38980852e-01, -9.95956516e-01,
         1.46296450e+00, -1.60892705e+00]])

In [132]:
ypred=model.predict(xtest_scaled)

## Evaluation

In [136]:
from sklearn.metrics import mean_squared_error

In [138]:
mean_squared_error(ytest,ypred)

4.2044125373225585

## Saving the Model

In [143]:
import joblib

In [145]:
joblib.dump(model,"model.pkl")
joblib.dump(encoder,"encoder.pkl")
joblib.dump(scaler,"scaler.pkl")

['scaler.pkl']